version: "3.2"
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - type: volume
        source: mongodb_data_volume
        target: /data/db
volumes:
  mongodb_data_volume:
    external: true

# Create a persistent volume with
# docker volume create mongodb_data_volume